project:
  type: website
  output-dir: docs

website:
  title: "AAVQS"
  description: "O maior grupo de pesquisa sobre SDA em linha reta do mundo!"
  favicon: fav.png
  navbar:
    logo: logo.png
    right:
      - href: index.qmd
        text: Início
      - equipe.qmd
      - text: Linhas de Pesquisa
        menu:
          - text: Agrupamento simultâneo de objetos e variáveis baseado em funções de kernel
            href: project1.qmd
          - text: Agrupamento de séries temporais tipo-intervalo baseado em distâncias kernelizadas e adaptativas
            href: project2.qmd
          - text: Aprendizagem de máquina em espaços de dissimilaridade simbólicos
            href: project3.qmd
          - text:  Métodos de agrupamento difuso usando graus de pertinência multivariados
            href: project4.qmd
  page-footer:
    left: "Made with [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, [Marcelo Ferreira](https://marcelorpf.github.io)."

format:
  html:
    self-contained: false
    theme: lumen
    css: styles.css
    toc: true

editor: visual

