project:
  type: website
  output-dir: docs

website:
  title: "AAVQS"
  description: "O maior grupo de pesquisa sobre SDA em linha reta do mundo!"
  favicon: fav.png
  navbar:
    logo: logo.png
    right:
      - href: index.qmd
        text: Início
      - equipe.qmd
      - projects.qmd
      - results.qmd
  page-footer:
    left: "Made with [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, [Marcelo Ferreira](https://marcelorpf.github.io)."

format:
  html:
    self-contained: false
    theme: lumen
    css: styles.css
    toc: true

editor: visual

