---
title: "Linhas de Pesquisa"
---

## Agrupamento simultâneo de objetos e variáveis baseado em funções de kernel

::: {style="text-align: justify"}
Nessa linha de pesquisa, pretendemos desenvolver métodos de coclustering baseados em funções de kernel. Objetivamos desenvolver tais métodos sob ambas as perspectivas de métodos baseados em funções de kernel: kernelização da métrica, onde o representante de cada grupo é descrito no espaço original, e agrupamento no espaço de características, onde o representante de cada grupo é descrito no espaço de kernels, e também considerando dois tipos de agrupamentos particionais: exclusivo (hard ou crisp), onde uma observação pertence a um, e apenas um, grupo, e não-exclusivo (fuzzy), onde uma observação pode pertencer a todos os grupos com um certo grau de pertencimento. Os algoritmos correspondentes serão implementados em linguagem C/C++, [R](http://www.r-project.org) e/ou Python.
:::

## Agrupamento de séries temporais tipo-intervalo baseado em distâncias kernelizadas e adaptativas

::: {style="text-align: justify"}
Nessa linha de pesquisa, pretendemos desenvolver, implementar e avaliar novos algoritmos para agrupamento de séries temporais tipo-intervalo baseados em kernel, considerando os enfoques de kernelização da métrica e agrupamento espaço de características, e em distâncias adaptativas. Os algoritmos correspondentes serão implementados em linguagem [R](http://www.r-project.org).
:::

## Aprendizagem de máquina em espaços de dissimilaridade simbólicos

::: {style="text-align: justify"}
Nessa linha de pesquisa, pretendemos desenvolver técnicas para transformar dados simbólicos em dados clássicos, sem desconsiderar as correlações implícitas das variáveis simbólicas, abrindo caminho para o uso de todo o universo de técnicas de Aprendizagem de Máquina para dados clássicos, sem precisar adaptá-las para dados simbólicos. Para isso, esta atividade irá usar distâncias e/ou métodos de agrupamento simbólicos, para obter representações dos dados simbólicos em um novo espaço de dissimilaridades, em que cada instância será representada pelas suas distâncias para outras instâncias de dados. Essas distâncias assumem valores numéricos que podem então ser usados como entrada para o treinamento de métodos clássicos de Aprendizagem de Máquina. Os algoritmos correspondentes serão implementados em Python.
:::

## Métodos de agrupamento difuso usando graus de pertinência multivariados

::: {style="text-align: justify"}
Nessa linha de pesquisa, pretendemos desenvolver métodos de agrupamento difuso para vetores numéricos. Esses métodos são menos sensíveis a situações em que dados ruidosos estão presentes no conjunto de dados. O grau pertinência de um elemento do conjunto de dados para um grupo é definido levando em conta a similaridade entre esse elemento e o representante de cada grupo de acordo com informação inerente a cada variável. Além disso, os métodos usam medidas de distância que consideram vetores de pesos diferentes por grupo e variável. Esses valores de peso podem mudar a cada iteração dos algoritmos a fim de melhorar o desempenho dos mesmos. Os algoritmos serão implementados em [R](http://www.r-project.org).
:::
